name: Sync (duckduckgpt/ to kudoai/duckduckgpt/) && (duckduckgpt/greasemonkey/ to adamlui/userscripts/chatgpt/duckduckgpt/)

on:
  push:
    branches: [ master, main ]
    paths:
      - 'duckduckgpt/**'

jobs:
  build:
    if: github.event.commits[0].committer.username != 'auto-sync-bot'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/chatgpt-addons
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-addons
          path: adamlui/chatgpt-addons

      - name: Checkout kudoai/duckduckgpt
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: kudoai/duckduckgpt
          path: kudoai/duckduckgpt

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Sync README.md between directories
        run: |
          if [ "$(stat -c %y "${{ github.workspace }}/adamlui/chatgpt-addons/duckduckgpt/README.md")" > "$(stat -c %y "${{ github.workspace }}/adamlui/chatgpt-addons/duckduckgpt/greasemonkey/README.md")" ]; then
            cp -f "${{ github.workspace }}/adamlui/chatgpt-addons/duckduckgpt/README.md" "${{ github.workspace }}/adamlui/chatgpt-addons/duckduckgpt/greasemonkey/README.md"
          elif [ "$(stat -c %y "${{ github.workspace }}/adamlui/chatgpt-addons/duckduckgpt/greasemonkey/README.md")" > "$(stat -c %y "${{ github.workspace }}/adamlui/chatgpt-addons/duckduckgpt/README.md")" ]; then
            cp -f "${{ github.workspace }}/adamlui/chatgpt-addons/duckduckgpt/greasemonkey/README.md" "${{ github.workspace }}/adamlui/chatgpt-addons/duckduckgpt/README.md"
          fi

      - name: Sync duckduckgpt/ to kudoai/duckduckgpt/
        run: rsync -avh ${{ github.workspace }}/adamlui/chatgpt-addons/duckduckgpt/ ${{ github.workspace }}/kudoai/duckduckgpt/

      - name: Sync duckduckgpt/greasemonkey/ to adamlui/userscripts/chatgpt/duckduckgpt/
        run: rsync -avh --delete ${{ github.workspace }}/adamlui/chatgpt-addons/duckduckgpt/greasemonkey/ ${{ github.workspace }}/adamlui/userscripts/chatgpt/duckduckgpt/

      - name: Push to adamlui/chatgpt-addons
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@chatgptevo.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/chatgpt-addons`]'
          file_pattern: 'duckduckgpt/*' 
          repository: adamlui/chatgpt-addons

      - name: Push to kudoai/duckduckgpt
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@chatgptevo.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/chatgpt-addons`]'
          file_pattern: '*'
          repository: kudoai/duckduckgpt

      - name: Push to adamlui/userscripts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@chatgptevo.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/chatgpt-addons`]'
          file_pattern: 'chatgpt/duckduckgpt/*'
          repository: adamlui/userscripts