name: Sync (chatgpt-widescreen/ to adamlui/chatgpt-widescreen/) && (chatgpt-widescreen/greasemonkey/ to adamlui/userscripts/chatgpt/chatgpt-widescreen/)

on:
  push:
    branches: [ master, main ]
    paths:
      - 'chatgpt-widescreen/**'

jobs:
  build:
    if: github.event.commits[0].committer.username != 'auto-sync-bot'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/chatgpt-addons
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-addons
          path: adamlui/chatgpt-addons

      - name: Checkout adamlui/chatgpt-widescreen
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-widescreen
          path: adamlui/chatgpt-widescreen

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Sync README.md between directories
        run: |
          if [ "$(stat -c %y "${{ github.workspace }}/adamlui/chatgpt-addons/chatgpt-widescreen/README.md")" > "$(stat -c %y "${{ github.workspace }}/adamlui/chatgpt-addons/chatgpt-widescreen/greasemonkey/README.md")" ]; then
            cp -f "${{ github.workspace }}/adamlui/chatgpt-addons/chatgpt-widescreen/README.md" "${{ github.workspace }}/adamlui/chatgpt-addons/chatgpt-widescreen/greasemonkey/README.md"
          elif [ "$(stat -c %y "${{ github.workspace }}/adamlui/chatgpt-addons/chatgpt-widescreen/greasemonkey/README.md")" > "$(stat -c %y "${{ github.workspace }}/adamlui/chatgpt-addons/chatgpt-widescreen/README.md")" ]; then
            cp -f "${{ github.workspace }}/adamlui/chatgpt-addons/chatgpt-widescreen/greasemonkey/README.md" "${{ github.workspace }}/adamlui/chatgpt-addons/chatgpt-widescreen/README.md"
          fi

      - name: Sync chatgpt-widescreen/ to adamlui/chatgpt-widescreen/
        run: rsync -avh ${{ github.workspace }}/adamlui/chatgpt-addons/chatgpt-widescreen/ ${{ github.workspace }}/adamlui/chatgpt-widescreen/

      - name: Sync chatgpt-widescreen/greasemonkey/ to adamlui/userscripts/chatgpt/chatgpt-widescreen/
        run: rsync -avh --delete ${{ github.workspace }}/adamlui/chatgpt-addons/chatgpt-widescreen/greasemonkey/ ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-widescreen/

      - name: Push to adamlui/chatgpt-addons
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@chatgptevo.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/chatgpt-addons`]'
          file_pattern: 'chatgpt-widescreen/*'
          repository: adamlui/chatgpt-addons

      - name: Push to adamlui/chatgpt-widescreen
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@chatgptevo.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/chatgpt-addons`]'
          file_pattern: '*'
          repository: adamlui/chatgpt-widescreen

      - name: Push to adamlui/userscripts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@chatgptevo.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/chatgpt-addons`]'
          file_pattern: 'chatgpt/chatgpt-widescreen/*'
          repository: adamlui/userscripts